AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'config/*'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'bin/*'
    - 'Gemfile'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
